### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by hulthe** [algebraicdb/algebraicdb#19]
We should add a license to make our project free-software.

I haven't done _that_ much research but here are a few options that might be viable:
- **MIT**
  Used by a most open source projects on GitHub since its pretty lax about enforcing freedoms.
  Probably the way to go if you don't buy super-hard into the free-software jazz.
- **Apache**
  Pretty close to MIT, difference being that if you change any Apache-licensed code, "you must state so".
- **GPL**
  Probably the strongest free-software license. Slightly controversial in that it has a tendency to "infect" projects that depend on other GPL-licensed code.
- **MPL**
  Not as popular as the other ones. Used by Mozilla. Might be a good balance between free-software-ness and not getting in the way since it applies itself on a per-file basis and not per-project.

---

Links:
- https://choosealicense.com/licenses/
- https://github.com/search?q=license%3Amit
- https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#searching-github-by-license-type

**Comment by feffes** [comment]
I was thinking of leaving this unlicensed until after the project is over, which I think seems reasonable. I've thought about it a bit though and would strongly prefer GPLv3.

EDIT: To clarfiy, I know there are some issues with not licensing under MIT or Apache for rust libraries, but I think that strictly the actual database should be licensed under GPLv3  but I think that any potential client libraries should be licensed under the preferred license for that language, which for rust is dual MIT and Apache licenses.

**Comment by feffes** [comment]
We should also make sure that the license we use complies with the libraries used.

**Comment by hulthe** [comment]
If we want to be able to make the db embeddable in other applications as a library, then GPL _might_ be problematic, but tbh i'm not entirely sure how much so.
