### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by hulthe** [algebraicdb/algebraicdb#29]
We should and could easily add a bunch of tests which spin up a database, run a few queries, and then fail if the output is anything other than expected.

e.g. two files
```sql
-- test1/input.sql
CREATE TABLE t(a Integer);
INSERT INTO t(a) VALUES (42);
SELECT a FROM t;
```
```sql
-- test1/output.sql
Table created.
1 row inserted.
[42]
```

Along with a script iterating over all test-folders.

**Comment by feffes** [comment]
This exists now.
Issues regarding said tests or asking for new tests should be brought up in new issues.
