### ISSUE TITLE
Improve conga

### ISSUE THREAD

**Issue by Baloo1** [algebraicdb/algebraicdb#34]
Right now conga needs a lot of fixes. For example handling escape characters

https://github.com/algebraicdb/algebraicdb/blob/17495f14eced907e6aab1baa39261d56c96fd538/src/api/tcp_api.rs#L62-L63

**Comment by hulthe** [comment]
The following regex could be used to find non-escaped semicolons:
```
 ;(?=([^"\\]*(\\.|"([^"\\]*\\.)*[^"\\]*"))*[^"]*$)
```

There is also a crate called regex ;)
