### ISSUE TITLE
Handle recursive types in check_create_type

### ISSUE THREAD

**Issue by Baloo1** [algebraicdb/algebraicdb#45]
For a type:
MyVariant = Var1 TypeA | Var2 TypeB TypeC
We have to check that the type name MyVariant is not taken as well ass that Type{A,B,C} exists

https://github.com/algebraicdb/algebraicdb/blob/32d204074fd8c338a134560318a1dc4b25d632ae/src/typechecker.rs#L312-L337

**Comment by hulthe** [comment]
A recursive type is one that contains itself.
e.g.

```haskell
data T = Another T | Nil
```

**Comment by feffes** [comment]
if needed we could probably introduce a keyword that signifies recursivity for a certain type similar to OCaml recursive function definitions.

`CREATE TYPE Whatever AS REC VARIANT { ... }`
or `CREATE REC TYPE Whatever AS VARIANT {...}` or something along those lines. might not even be needed though.
