### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by Baloo1** [algebraicdb/algebraicdb#6]
The product will be benchmarked to compare it with other relational databases. The focus of the benchmarking is to assess how the performance is affected with the implementation of algebraic datatypes.

Benchmarking parts of the code, and stress testing the new implementation along with an existing database, will be done to examine how sum-types affect the performance of queries. The point is not to outperform existing databases, but to hopefully gain important data on the impact of the new type system.

To achieve this we need to define the benchmark requirements and implement the benchmarker

**Comment by hulthe** [comment]
We are in a position where we could start looking into profiling our code with `cargo-flamegraph`
