### ISSUE TITLE
Write Ahead Log

### ISSUE THREAD

**Issue by feffes** [algebraicdb/algebraicdb#77]
This is a thing, that would be nice if it existed.

After this is implemented we can make pretty accurate benchmarks to compare with other databases.

Right now the idea is to have a single file that we first write modification queries to, and after that handle the dbms state.
 1. Write query to logfile.
 2. Write commit transaction to dbms state.
 3. Increment dbms tracker.

At a later point the dbms state can be written as a whole onto disk, locking all tables for a short time.

We need to probably refactor `resource_manager` in local and create a new function that handles the overarching transaction handling.

**Comment by hulthe** [comment]
Implemented in #80
